name: Build Releases

on:
  push:

permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Zip archive
        run: |
             cd src
             zip -r ../kernel-su-hosts.zip *

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"         
        with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: v1.0
            title: v1.0
            prerelease: true
            files: |
              *.zip

